---
version: '2'
services:
  puppenc-api:
    #image: puppenc/api:latest
    image: puppenc/api:v2
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      -  $PWD:/puppenc
    links:
      - puppenc-mysql
    entrypoint:
      - python
      - run.py
    environment:
      PUPPENC_SETTINGS: 'config.py'      
  puppenc-mysql:
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'puppenc'
      MYSQL_DATABASE: 'puppenc'
